- name: Basic for Utility SYstem
  hosts: utility*
  # hosts: git,control
  gather_facts: false
  remote_user: devops
  become: true

  tasks:
    - name: Creata a user by default builtin modules
      ansible.builtin.user:
        name: richard
        comment: "Richard User Student USER"
    # - name: Use a module from VEdnor CUstom Collections 
    #   cisco.aci.aci_snmp_user:
    #     host: apic
    #     username: admin



    # - name: Create a file
    #   copy:
    #     content: "Hello Richard"
    #     dest: /tmp/file1

    # - name: Read passwd file
    #   command: tail -4 /etc/passwd

    # - name: Read Shadow file
    #   command: tail -4 /etc/shadow
