- name: Cisco Playbook
  hosts: iosxe1.lab.example.com 
  gather_facts: false
  tasks:
    - name: Run commands that require answering a prompt
      cisco.ios.ios_command:
        commands:
          - command: "clear counters GigabitEthernet2"
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: "y"
          # - command: "clear counters GigabitEthernet3"
          #   prompt: "[confirm]"
          #   answer: "\r"
    - name: run command expecting user confirmation
      ansible.netcommon.cli_command:
        command: show interface summary
        prompt: Press any key to continue
        answer: y
        newline: false

    - name: reload
      cisco.ios.ios_command:
        commands:
          - command: 'reload'
            prompt: 'Proceed with reload[confirm]'
            answer: 'y'
        # wait_for: 30
    - name: Wait for the second network interface
      cisco.ios.ios_command:
        commands:
          - show interfaces
        wait_for:
          - result[0] contains 'GigabitEthernet1 is up'
        interval: 2
        retries: 19
    - name: Change Interface Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Configures_ANSIBLE11"
            enabled: true
      register: larson_capture
          # - name: GigabitEthernet2
          #   description: "Configures_ANSIBLE22"
          #   enabled: true

    - name: Print Full output
      ansible.builtin.debug:
        msg: "{{ larson_capture }}"

    - name: Print Selected output
      ansible.builtin.debug:
        msg: "{{ larson_capture.changed }}"
      notify:
        - Banner for the Device

  handlers:
    - name: Banner for the Device
      cisco.ios.ios_banner:
        banner: login
        text: "Testing11"
        state: present
      # when: larson_capture.changed == true
