- name: Cisco Playbook
  hosts: "{{ ferguson_systems }}"
  gather_facts: false
  tasks:
    - name: Ping a System
      cisco.ios.ios_ping:
        dest: workstation.lab.example.com

    - name: Configure a Cisco IOS device
      cisco.ios.ios_config:
        lines:
          - service timestamps debug datetime msec
      when: meme is not defined

    - name: Change Interface Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Configures_ANSIBLE11"
            enabled: true
      register: larson_capture
          # - name: GigabitEthernet2
          #   description: "Configures_ANSIBLE22"
          #   enabled: true

    - name: Print Full output
      ansible.builtin.debug:
        msg: "{{ larson_capture }}"

    - name: Print Selected output
      ansible.builtin.debug:
        msg: "{{ larson_capture.changed }}"
      notify:
        - Banner for the Device

  handlers:
    - name: Banner for the Device
      cisco.ios.ios_banner:
        banner: login
        text: "Testing11"
        state: present
      # when: larson_capture.changed == true
