- name: Handlers Demo / Dependency Task Playbook
  hosts: iosxe1.lab.example.com
  gather_facts: false
  tasks:

    - name: Change Interface Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Configures_ANSIBLE1"
            enabled: true
          - name: GigabitEthernet2
            description: "Configures_ANSIBLE22"
            enabled: true
      notify:
        - Save Configurations 

    - name: Banner for the Device
      cisco.ios.ios_banner:
        banner: login
        text: "Testing"
        state: present
      notify:
        - Save Configurations 

  handlers:
    - name: Save Configurations
      cisco.ios.ios_config:
        save_when: always



