- name: Import a Variable playbook
  ansible.builtin.import_playbook: variable_demo.yml

- name: Very Large Playbook / Integration PlayBook
  hosts: iosxe1*
  gather_facts: false
  tasks:
    # - name: Import a Task File
    #   ansible.builtin.import_tasks:
    #     file: tasks/cisco_acl.yml
    #   # when: meme is defined

    # - name: Include a Task File
    #   ansible.builtin.include_tasks:
    #     file: tasks/cisco_vlan.yml
      # when: meme is defined
      #
    - name: Loop only for include NOT import
      ansible.builtin.include_tasks:
      # ansible.builtin.import_tasks:
        file: "{{ item }}"
      loop:
        - tasks/cisco_acl.yml
        - tasks/cisco_vlan.yml

- name: Import a Second playbook
  ansible.builtin.import_playbook: multiple_play.yml
