- name: Play1 on Cisco
  hosts: iosxe1.lab.example.com
  gather_facts: false
  tasks:
    - name: Change Interface Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Configures_ANSIBLE1"
            enabled: true
          - name: GigabitEthernet2
            description: "Configures_ANSIBLE22"
            enabled: true

    - name: Banner for the Device
      cisco.ios.ios_banner:
        banner: login
        text: "Testing"
        state: present

- name:  Play 2 on Juniper
  hosts: 
    - junos1.lab.example.com
    - junos2.lab.example.com
  gather_facts: false
  tasks:
    - name: Enable the netconf service on port 830
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: present
      vars:
        ansible_connection: ansible.netcommon.network_cli

    - name: Backup Junos configurations
      junipernetworks.junos.junos_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}.txt"

    - name: Disable the netconf service on port 830
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: absent
      vars:
        ansible_connection: ansible.netcommon.network_cli
