- name: Survey Demo Playbook
  hosts: all
  gather_facts: false
  tasks:

    - name: Change Interface Description
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "{{ eth_desc }}"
            enabled: true

    - name: Banner for the Device
      cisco.ios.ios_banner:
        banner: login
        text: "{{ banner_desc }}"
        state: present
